spring.profiles.active: local

spring:
  config:
    import:
      - mysql.yml
      - swagger.yml
      - crypto.yml
      - mail.yml
      - redis.yml
      - jwt.yml
      - s3.yml
  data:
    web:
      pageable:
        one-indexed-parameters: true

server:
  port: ${APPLICATION_PORT:8080}
  tomcat:
    max-connections: 10000
    threads:
      max: 200
      min-spare: 20

---
spring.config.activate.on-profile: local

spring:
  config:
    import:
      - optional:classpath:env.properties

logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: dev

logging:
  level:
    root: INFO
  structured:
    format:
      file: ecs
  file:
    path: ${LOG_FILE_PATH:./logs}

---
spring.config.activate.on-profile: prod