s3:
  endpoint: ${S3_ENDPOINT}
  region: ${S3_REGION}
  bucket-name: ${S3_BUCKET_NAME}
  bucket-prefix: ${S3_BUCKET_PREFIX}
  credentials:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB