name: Create Jira Test
on:
  issues:
    types:
      - opened

jobs:
  create-issue:
    name: Create Jira Test
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue uses test template
        id: check_template
        run: |
          BODY="${{ github.event.issue.body }}"
          if [[ $BODY == *"Test 상위 작업 Ticket Number"* ]]; then
            echo "is_test_template=true" >> $GITHUB_OUTPUT
          else
            echo "is_test_template=false" >> $GITHUB_OUTPUT
          fi
      - name: Exit if not test template
        if: steps.check_template.outputs.is_test_template != 'true'
        run: exit 0

      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: |
            .github/ISSUE_TEMPLATE/test_issue_template.yml
      - name: Log Issue Parser
        run: |
          echo '${{ steps.issue-parser.outputs.jsonString }}'
      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}
            ${{ github.event.issue.body }}
          mode: md2jira

      - name: Create Issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: WRKR
          issuetype: Task
          summary: "${{ github.event.issue.title }}"
          description: "${{ steps.md2jira.outputs.output-text }}"
          fields: |
            {
              "parent": {
                "key": "${{ steps.issue-parser.outputs.issueparser__qa_test___ticket_number }}"
              }
            }
      - name: Checkout release code
        uses: actions/checkout@v4
        with:
          ref: release
          token: ${{ secrets.PAT_TOKEN }}

      - name: Create branch with Ticket number
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b hotfix/test/${{ steps.create.outputs.issue }}
          git push origin hotfix/test/${{ steps.create.outputs.issue }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Update issue title
        uses: actions-cool/issues-helper@v3
        with:
          actions: "update-issue"
          token: ${{ secrets.PAT_TOKEN }}
          title: "${{ steps.create.outputs.issue }} ${{ github.event.issue.title }}"
