name: Deploy Backend

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: "pj0224/backend-tms"
      IMAGE_TAG: "${{ github.run_number }}"
      APP_NAME: "wrkr-backendservice-app"
      
      DOCKER_USERNAME: "parkjj000224@gachon.ac.kr"
      DOCKER_PASSWORD: "qkrwjdwo2$"
      
      TARGET_HOST: "210.109.14.158"
      SSH_PRIVATE_KEY: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAQEAooa4VpYySjHxOGUKDfe2/2f/JoG/fXM2Euq1l91juBgRHNr9HCRi
        mcIp2vwicBSnnMbIMoeG6dtXrIkrGAd1A8h071JqhR3ameG/0yvZFY7Cf1XK0xZV8rNSS/
        UxMIZ0xhiOdwY+bgedu7vtPx/0k8kvhCzKhnzif355SPjCn62BbXStrxxVEd7mXq1lqh6u
        XEjrl22FFfCr0XPqvafQAPtf4vndPKO6OiQnL/Dde4JOJomFroUMfhBqtSl3g7QkNSIUk8
        g98ELpMIzEyKndERW/KZBbuJFGFtgVsiJjJ57N2nqhL2EjyTNFP8WVQAQDZOI0FK1Xw3Cg
        GPZOu7MDhQAAA9A1Zq4LNWauCwAAAAdzc2gtcnNhAAABAQCihrhWljJKMfE4ZQoN97b/Z/
        8mgb99czYS6rWX3WO4GBEc2v0cJGKZwina/CJwFKecxsgyh4bp21esiSsYB3UDyHTvUmqF
        HdqZ4b/TK9kVjsJ/VcrTFlXys1JL9TEwhnTGGI53Bj5uB527u+0/H/STyS+ELMqGfOJ/fn
        lI+MKfrYFtdK2vHFUR3uZerWWqHq5cSOuXbYUV8KvRc+q9p9AA+1/i+d08o7o6JCcv8N17
        gk4miYWuhQx+EGq1KXeDtCQ1IhSTyD3wQukwjMTIqd0RFb8pkFu4kUYW2BWyImMnns3aeq
        EvYSPJM0U/xZVABANk4jQUrVfDcKAY9k67swOFAAAAAwEAAQAAAQAB8v+u+iosPaEY/g06
        0ae+NG8Y9SFozcLuQyZeZedWQ+Ogpve2KLGOCogZ+kAne/fup2urP3jcwSayCQsdRKmgm/
        zbCfABHLSMd+qnC7WUzpuCj3LZSUFKod/wzUYDwPkRjyXWQ5roEutPXxefVDDIvPb27NqY
        9lJ5GPk3aNRcueEVSgxjLicEEgnVRTcEEJSBi5zUaiyUZ4W7ND5Gds3LbYii57FfN17a1Y
        hdV90xrDOGMsuQPh/hhFVhv9pUWlKy0q2qN/UVjyaIsFXYsVJbC3ARXxgJbsfrJ+zaGN5R
        YJXnTm1RT1tYiDQ+ncLEXbLQXZjVW0o55XwBChMrYnTZAAAAgDc5ijanKqNAuDobzVHoHj
        HmHOPUpO3YeFPbzqYliRcV0wPgKH6nxCm2X+eWWre5XBSLQurD9VCp6D8ReyQAuASeBQZ3
        NGEI6gDAWrxE07pwtv0xKRr2ZMPNGIfU785qlFi1x5YGKAhKvWSD9YUVarAeHoMmpR/hm1
        v5YE2ZyuLRAAAAgQDcMYz9087iYScZYMFRjNtVrrVnd+l1UKFlXEp0vQfN/+9tvQG5KYXq
        akgeazpOwqMXYFHiDBReiZmzWqqeKXej++LgYDs0/z4EAZ8rwUf/QilfE2s9/6J3WTjSOx
        JJ2rHghbwmj7ArYfKRYpksv2afSea+u1TrU82Z49109HPPOwAAAIEAvPSIsBudgZmTWpIZ
        lVN1+DrkKt9aDFNIEM5pd7nsIyZlKq1aaXpyeHUwU2TiBrsF6HnmSrTH7UHpEd76lte+cD
        d+4dU4lH+ZYk3pg9lnYznR9P5Q89x+U6WSO6QZvBIBWs0lMmdzhnHSXPXsxZx5LgSzafbx
        o2sr2b3dgV0wzD8AAAAWdWJ1bnR1QGhvc3QtMTAtMC0xLTIxNAECAwQF
        -----END OPENSSH PRIVATE KEY-----
        
      DATABASE_HOST: "210.109.15.246"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "wrkrdb_new"
      DATABASE_USERNAME: "wrkr"
      DATABASE_PASSWORD: "wrkrdb1!"

      PK_CRYPTO_ALGORITHM: "AES"
      PK_CRYPTO_SECRET: "GREATTEAM4WRKR12"
      SWAGGER_SERVER_URL: "https://www.tickety.co.kr"

      GMAIL_USERNAME: "wrkr.kea"
      GMAIL_APP_PASSWORD: "sgixfwuaoavobuba"

      LOG_FILE_PATH: "./logs"
      
      REDIS_HOST: "210.109.53.90"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "tickety1!"
      
      JWT_SECRET_KEY: "xhZ03FOyeiXRNTs3tXoUXzWazy/fxMqhIp7ehrCyTWoyeONltC/ZIa9oFtMido7orXZpM5kYCgFH4sJ9Kwli3Q=="
      JWT_REFRESH_EXPIRATION: "1209600"
      JWT_ACCESS_EXPIRATION: "1800000"
      
      S3_BUCKET_NAME: "wrkr-attachment"
      S3_ENDPOINT: "https://objectstorage.kr-central-2.kakaocloud.com"
      S3_REGION: "kr-central-2"
      S3_ACCESS_KEY: "14acf112af4f42b5a18653325f3beb01"
      S3_SECRET_KEY: "385b0d58202628b04e81b9590cffaaf22024ec6a3ec745e37bba506cae6e392d5dad87"
      
      KAKAOWORK_BASE_URL: "https://api.kakaowork.com"
      KAKAOWORK_APP_KEY: "a5c86677.4405c744fdf2410fa88c65259d1ffa75"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Gradle Project
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon --build-cache clean build -x test

      - name: Log in to DockerHub
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Clean up Docker Images
        run: docker image prune -af

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.TARGET_HOST }}
          username: ubuntu
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            docker rm -f $APP_NAME || true
            docker run -d --name $APP_NAME \
              -p 8080:8080 \
              --restart on-failure \
              -e DATABASE_HOST=${{ env.DATABASE_HOST }} \
              -e DATABASE_PORT=${{ env.DATABASE_PORT }} \
              -e DATABASE_NAME=${{ env.DATABASE_NAME }} \
              -e DATABASE_USERNAME=${{ env.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ env.DATABASE_PASSWORD }} \
              
              -e PK_CRYPTO_ALGORITHM=${{ env.PK_CRYPTO_ALGORITHM }} \
              -e PK_CRYPTO_SECRET=${{ env.PK_CRYPTO_SECRET }} \
              -e SWAGGER_SERVER_URL=${{ env.SWAGGER_SERVER_URL }} \
              
              -e GMAIL_USERNAME=${{ env.GMAIL_USERNAME }} \
              -e GMAIL_APP_PASSWORD=${{ env.GMAIL_APP_PASSWORD }} \
              
              -e LOG_FILE_PATH=${{ env.LOG_FILE_PATH }} \
              
              -e REDIS_HOST=${{ env.REDIS_HOST }} \
              -e REDIS_PORT=${{ env.REDIS_PORT }} \
              -e REDIS_PASSWORD=${{ env.REDIS_PASSWORD }} \
              
              -e JWT_SECRET_KEY=${{ env.JWT_SECRET_KEY }} \
              -e JWT_REFRESH_EXPIRATION=${{ env.JWT_REFRESH_EXPIRATION }} \
              -e JWT_ACCESS_EXPIRATION=${{ env.JWT_ACCESS_EXPIRATION }} \
              
              -e S3_BUCKET_NAME=${{ env.S3_BUCKET_NAME }} \
              -e S3_ENDPOINT=${{ env.S3_ENDPOINT }} \
              -e S3_REGION=${{ env.S3_REGION }} \
              -e S3_ACCESS_KEY=${{ env.S3_ACCESS_KEY }} \
              -e S3_SECRET_KEY=${{ env.S3_SECRET_KEY }} \
              
              -e KAKAOWORK_BASE_URL=${{ env.KAKAOWORK_BASE_URL }} \
              -e KAKAOWORK_APP_KEY=${{ env.KAKAOWORK_APP_KEY }} \
              
              -v /etc/localtime:/etc/localtime:ro \
              -v /etc/timezone:/etc/timezone:ro \
              $IMAGE_NAME:$IMAGE_TAG
